import { Router } from "express";
import * as c from "../controllers/authController.js";
import { protect } from "../middleware/auth.js";
const r = Router();
r.post("/register", c.register);
r.post("/login", c.login);
r.post("/forgot-password", c.forgotPassword);
r.post("/reset-password/:token", c.resetPassword);
r.get("/me", protect, c.me);
r.patch("/change-password", protect, c.changePassword);
export default r;
